---
- hosts: all
  become: yes
  tasks:
  - name: i want to install apache2 on ubuntu 16.04
    apt:
      name: apache2
      state: present

  - name: i want to start my webserver
    service: 
      name: apache2
      state: started
      